name: 'crypto_analytics'
version: '1.0.0'
config-version: 2

# Project profile (matches profiles.yml)
profile: 'crypto_analytics'

# Source code paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Model configurations
models:
  crypto_analytics:
    # Bronze layer (not needed - raw tables created by init_db.sql)

    # Silver layer - cleaned and validated
    silver:
      +materialized: incremental
      # Don't set schema here - use target schema from profiles.yml
      +on_schema_change: append_new_columns
      +tags:
        - "silver"

    # Gold layer - business metrics
    gold:
      +materialized: table
      +schema: gold
      +tags:
        - "gold"

# Seeds configuration
seeds:
  crypto_analytics:
    +schema: seeds
    +quote_columns: false

# Snapshots configuration
snapshots:
  crypto_analytics:
    +target_schema: snapshots
    +unique_key: id
    +strategy: timestamp
    +updated_at: updated_at

# Vars - global variables
vars:
  # Date range for incremental models
  start_date: '2024-01-01'

  # Crypto symbols we're tracking
  crypto_symbols: ['BTC-USD', 'ETH-USD', 'XRP-USD', 'ADA-USD', 'DOGE-USD', 'BNB-USD', 'DOT-USD', 'LTC-USD', 'LINK-USD', 'MATIC-USD']
