# dbt profiles configuration for Crypto Analytics Platform
crypto_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: airflow
      password: airflow
      dbname: airflow
      schema: silver
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,bronze,silver,gold

    prod:
      type: postgres
      host: postgres
      port: 5432
      user: airflow
      password: airflow
      dbname: airflow
      schema: silver
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,bronze,silver,gold
